### ISSUE TITLE
horizontal overflow of the page

### ISSUE THREAD

**Issue by MartyMiniac** [satyabrata-mishra/Rock-Paper-Scissor-Game#1]
I am not sure what exactly is causing the problem but i was able to replicate the problem on hovering over any of the <a></a> tags

I think the cause of problem is changing border in the hover selector tag.
I was able to fix the problem by omitting this line https://github.com/satyabrata-mishra/Rock-Paper-Scissor-Game/blob/603ed2deeaf9013b5819d5073c08339289c2c8b4/Rock-Paper-Sissor-Game/css/singleplayer.css#L36

**Comment by satyabrata-mishra** [comment]
yes line 36 was causing overflow
